### ISSUE TITLE
feature request: obscure password entered by user

### ISSUE THREAD

**Issue by ianloefgren** [ianloefgren/project1#1]
When a user types their password, it is displayed as plain-text, instead of a series of dots or asterisks.

**Comment by TannerQuigley** [comment]
Just implemented the code and sent a pull request.

**Comment by ianloefgren** [comment]
Thank you! This should only work for Unix correct? Or does this work on windows as well?

**Comment by TannerQuigley** [comment]
Yes just Unix. Tried to implement it for Windows but it would crash so I just left it with Unix.
